#!/usr/bin/env python3
"""
Daily casual game analysis digest.
Collects yesterday's published content, scores, deduplicates, translates,
and sends to Feishu at 09:30 each morning.
"""

import json
import hashlib
import datetime
import subprocess
import os
import re
import time
import sys
import sqlite3
from pathlib import Path

import feedparser
import requests
import anthropic
from bs4 import BeautifulSoup

# Load .env file from script directory
def _load_dotenv():
    env_file = Path(__file__).parent / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())

_load_dotenv()

SCRIPT_DIR = Path(__file__).parent
HISTORY_FILE = SCRIPT_DIR / "history.json"
LOG_FILE = SCRIPT_DIR / "digest.log"
WECHAT_FEEDS_FILE = SCRIPT_DIR / "wechat_feeds.json"
ARCHIVE_DIR = SCRIPT_DIR / "archive"
JPS_FOCUS_APPS_FILE = SCRIPT_DIR / "jps_focus_apps.json"

WEWE_RSS_DB = SCRIPT_DIR.parent / "tools/we-mp-rss-new/data/db.db"
ON_THIS_DAY_YEARS = 3   # look back this many years

FEISHU_USER_ID = os.environ.get("FEISHU_USER_ID", "")
FEISHU_CHAT_ID = os.environ.get("FEISHU_CHAT_ID", "")
DEDUP_DAYS = 7
MIN_SCORE = 3          # 1-2 = 广告/垃圾，3+ 全部保留并按类别展示
ENABLE_SOGOU_WECHAT = False
MAX_CANDIDATES_TO_SCORE = 80

# Domains that are never analysis articles
BLOCKED_DOMAINS = {
    # Official game sites
    "royalmatch.com", "candycrush.com", "king.com", "homescapes.com",
    "supercell.com", "playrix.com", "dreamgames.com",
    # App stores
    "apps.apple.com", "play.google.com", "appstore.com",
    # Social / video (not articles)
    "twitter.com", "x.com", "instagram.com", "tiktok.com",
    "facebook.com", "youtube.com", "youtu.be",
    # Job boards
    "linkedin.com", "zhipin.com", "lagou.com", "boss.zhipin.com",
}

RSS_FEEDS = [
    {"url": "https://www.deconstructoroffun.com/blog?format=rss", "name": "Deconstructor of Fun", "lang": "en"},
    {"url": "https://naavik.co/feed/", "name": "Naavik", "lang": "en"},
    {"url": "https://www.gamedeveloper.com/rss.xml", "name": "Game Developer", "lang": "en"},
    {"url": "https://www.gamesindustry.biz/feed/", "name": "GamesIndustry.biz", "lang": "en"},
    {"url": "https://mobilegamer.biz/feed/", "name": "Mobile Gamer Biz", "lang": "en"},
    {"url": "https://www.pocketgamer.biz/feed/", "name": "Pocket Gamer Biz", "lang": "en"},
    {"url": "https://gamelook.com.cn/feed", "name": "GameLook", "lang": "zh"},
    {"url": "https://sspai.com/feed", "name": "少数派", "lang": "zh"},
]


WE_MP_RSS_ORIGIN = "http://localhost:8001"  # we-mp-rss service (migrated from WeWe-RSS port 4000)

# RSSHub proxy for Xiaoyuzhou podcasts (no official public RSS)
RSSHUB_BASE = "https://rsshub.rssforever.com"

PODCAST_FEEDS = [
    {"id": "5e280fb0418a84a0461fc251", "name": "机核游戏频道"},
    {"id": "629f5ac8525536dd029364a6", "name": "游戏电波"},
    {"id": "67b80115fa4e559013358d5c", "name": "游戏个人谈"},
    {"id": "62294a6b07d0b5937b63b4d1", "name": "游戏章鱼"},
    {"id": "69e66497fd45bb93d7bbd0f3", "name": "HitBox碰撞盒游戏杂谈"},
    {"id": "687a45603f48f289ebaf2b2a", "name": "游你友我"},
    {"id": "659510f21519ccb1038bfe4a", "name": "游戏酒馆"},
]


def load_wechat_feeds():
    """Load subscribed feeds from local wechat_feeds.json (generated by sync_wewe_feeds.py)."""
    try:
        with open(WECHAT_FEEDS_FILE) as f:
            return json.load(f)
    except Exception as e:
        log(f"WeChat feeds file unavailable: {e}")
        return []


def load_jps_focus_apps():
    if not JPS_FOCUS_APPS_FILE.exists():
        return []
    with open(JPS_FOCUS_APPS_FILE) as f:
        apps = json.load(f)
    return [app for app in apps if app.get("name")]


def check_wechat_feeds():
    feeds = load_wechat_feeds()
    if not feeds:
        print("No WeChat RSS URLs configured yet.")
        print(f"Fill urls in: {WECHAT_FEEDS_FILE}")
        return 1

    failures = 0
    for feed_info in feeds:
        name = feed_info.get("name", "微信公众号")
        url = feed_info["url"]
        try:
            feed = feedparser.parse(url)
            entries = feed.entries[:3]
            status = getattr(feed, "status", "")
            if not entries:
                failures += 1
                print(f"[FAIL] {name}: no entries (status={status})")
                continue
            newest = entries[0]
            published = ""
            for attr in ("published", "updated"):
                val = getattr(newest, attr, "")
                if val:
                    published = val
                    break
            print(f"[OK] {name}: {len(feed.entries)} entries; newest={newest.title} {published}")
        except Exception as e:
            failures += 1
            print(f"[FAIL] {name}: {e}")

    return 1 if failures else 0

# Google News RSS search queries: (query, lang, hl, gl, ceid)
SEARCH_QUERIES = [
    ("Royal Match casual game analysis", "en", "en-US", "US", "US:en"),
    ("match-3 game design teardown analysis", "en", "en-US", "US", "US:en"),
    ("casual mobile game monetization breakdown", "en", "en-US", "US", "US:en"),
    ("puzzle game feature design analysis", "en", "en-US", "US", "US:en"),
    ("casual game live ops event design", "en", "en-US", "US", "US:en"),
    ("休闲游戏玩法设计分析", "zh", "zh-CN", "CN", "CN:zh-Hans"),
    ("三消游戏运营拆解", "zh", "zh-CN", "CN", "CN:zh-Hans"),
    ("消除游戏数值设计", "zh", "zh-CN", "CN", "CN:zh-Hans"),
    ("手游关卡设计分析", "zh", "zh-CN", "CN", "CN:zh-Hans"),
]

# Focus games — each generates an English Google News query
FOCUS_GAMES = [
    "Royal Match", "Gossip Harbor", "MONOPOLY GO", "Candy Crush Saga",
    "Kingshot", "Last War Survival", "Coin Master", "Township",
    "Gardenscapes", "Royal Kingdom", "Last Z", "Toon Blast",
    "Homescapes", "Tasty Travels", "Disney Solitaire",
]

# WeChat via Sogou (titles/summaries real, links open in browser via redirect)
WECHAT_QUERIES = [
    "休闲游戏拆解",
    "三消游戏分析",
    "Royal Match 分析",
    "手游关卡设计",
    "消除游戏运营",
    # Priority account targeted searches
    "王董的新游戏",
    "一枚游戏干饭人 游戏",
    "罗斯基 游戏分析",
    "游戏进化论",
    "Vergil游戏",
    "嘅噗喔呋啼 游戏",
]

# Priority WeChat public accounts — articles from these get +1 scoring bonus
PRIORITY_ACCOUNTS = {
    "王董的新游戏", "一枚游戏干饭人", "GAME游意思", "DennisLook",
    "游戏译文", "良明同学", "海外新游精选", "Enjoy出海开发者服务平台",
    "Vergil的游戏杂谈", "新游观察", "柠檬游戏说", "曾嵘胡扯的地方",
    "熊猫搞钱记", "龙虾游戏推荐", "游戏进化论", "无界游戏学社",
    "罗斯基", "Crazy Labs", "星空出海", "嘅噗喔呋啼",
}


def log(msg):
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line)
    with open(LOG_FILE, "a") as f:
        f.write(line + "\n")


ALLOWED_REDIRECT_DOMAINS = {"weixin.sogou.com"}  # redirect links that open WeChat articles


def _extract_domain(url):
    m = re.search(r"https?://(?:www\.)?([^/]+)", url)
    return m.group(1).lower() if m else ""


def filter_blocked(articles):
    kept = [a for a in articles if
            _extract_domain(a.get("url", "")) not in BLOCKED_DOMAINS
            or _extract_domain(a.get("url", "")) in ALLOWED_REDIRECT_DOMAINS]
    removed = len(articles) - len(kept)
    if removed:
        log(f"Blocked domains removed: {removed}")
    return kept


def load_history():
    if HISTORY_FILE.exists():
        with open(HISTORY_FILE) as f:
            return json.load(f)
    return {"articles": []}


def save_history(history, new_articles):
    cutoff = datetime.datetime.now() - datetime.timedelta(days=DEDUP_DAYS)
    history["articles"] = [
        a for a in history["articles"]
        if datetime.datetime.fromisoformat(a["date"]) > cutoff
    ]
    for article in new_articles:
        title_key = re.sub(r"\s+", "", article.get("zh_title", article["title"]).lower())
        history["articles"].append({
            "url_hash": hashlib.md5(article["url"].encode()).hexdigest(),
            "title_hash": hashlib.md5(title_key.encode()).hexdigest(),
            "title": article.get("zh_title", article["title"]),
            "url": article["url"],
            "date": datetime.datetime.now().isoformat(),
        })
    with open(HISTORY_FILE, "w") as f:
        json.dump(history, f, ensure_ascii=False, indent=2)


def _url_hash(url):
    return hashlib.md5(url.encode()).hexdigest()


def _title_hash(title):
    return hashlib.md5(re.sub(r"\s+", "", title.lower()).encode()).hexdigest()


def is_duplicate(article, history):
    uh = _url_hash(article["url"])
    th = _title_hash(article["title"])
    for h in history["articles"]:
        if h["url_hash"] == uh or h["title_hash"] == th:
            return True
    return False


def dedup_batch(articles):
    seen_u, seen_t, unique = set(), set(), []
    for a in articles:
        uh, th = _url_hash(a["url"]), _title_hash(a["title"])
        if uh in seen_u or th in seen_t:
            continue
        seen_u.add(uh)
        seen_t.add(th)
        unique.append(a)
    return unique


def strip_html(text):
    return re.sub(r"<[^>]+>", "", text or "").strip()


_TARGET_DATE: datetime.datetime | None = None  # set by --date flag


def _today_start():
    if _TARGET_DATE:
        return _TARGET_DATE + datetime.timedelta(days=1)  # "today" = day after target
    now = datetime.datetime.now()
    return datetime.datetime(now.year, now.month, now.day)


def _tomorrow_start():
    return _today_start() + datetime.timedelta(days=1)


def _yesterday_start():
    if _TARGET_DATE:
        return _TARGET_DATE  # "yesterday" = the target date itself
    return _today_start() - datetime.timedelta(days=1)


def _parse_date_text(text):
    text = (text or "").strip()
    if not text:
        return None

    now = datetime.datetime.now()
    if "刚刚" in text:
        return now

    m = re.search(r"(\d+)\s*分钟前", text)
    if m:
        return now - datetime.timedelta(minutes=int(m.group(1)))

    m = re.search(r"(\d+)\s*小时前", text)
    if m:
        return now - datetime.timedelta(hours=int(m.group(1)))

    m = re.search(r"(\d+)\s*天前", text)
    if m:
        return now - datetime.timedelta(days=int(m.group(1)))

    for pattern in (
        r"(20\d{2})[-/.年](\d{1,2})[-/.月](\d{1,2})",
        r"(\d{1,2})[-/.月](\d{1,2})",
    ):
        m = re.search(pattern, text)
        if not m:
            continue
        try:
            if len(m.groups()) == 3:
                year, month, day = map(int, m.groups())
            else:
                year = now.year
                month, day = map(int, m.groups())
            return datetime.datetime(year, month, day)
        except ValueError:
            return None

    return None


def _parse_published_date(text):
    text = (text or "").strip()
    if not text:
        return None

    for candidate in (text, text.replace("Z", "+00:00")):
        try:
            parsed = datetime.datetime.fromisoformat(candidate)
            if parsed.tzinfo:
                parsed = parsed.astimezone().replace(tzinfo=None)
            return parsed
        except ValueError:
            pass

    return _parse_date_text(text)


def _contains_old_year(article):
    current_year = datetime.datetime.now().year
    # Only check URL — titles/summaries legitimately reference past years in analysis
    url = article.get("url", "")
    for year_s in re.findall(r"(?<!\d)(20\d{2})(?!\d)", url):
        if int(year_s) < current_year:
            return True
    return False


def is_fresh(article, require_date=False):
    if _contains_old_year(article):
        return False

    published = article.get("published_at")
    if not published:
        return not require_date

    parsed = _parse_published_date(published)
    if not parsed:
        return not require_date

    return _yesterday_start() <= parsed < _today_start()


def filter_fresh(articles, require_date=False, label="Freshness"):
    kept = [a for a in articles if is_fresh(a, require_date=require_date)]
    removed = len(articles) - len(kept)
    if removed:
        log(f"{label} removed: {removed}")
    return kept


def sort_candidate_articles(articles):
    def parsed_time(article):
        parsed = _parse_published_date(article.get("published_at", ""))
        return parsed or datetime.datetime.min

    return sorted(
        articles,
        key=lambda a: (
            1 if a.get("priority") else 0,
            1 if str(a.get("source", "")).startswith("微信-") else 0,
            parsed_time(a),
        ),
        reverse=True,
    )


def fetch_rss():
    articles = []
    win_start = _yesterday_start()   # yesterday 00:00
    win_end = datetime.datetime.now()  # up to now (covers early-morning articles)
    for feed_info in RSS_FEEDS:
        try:
            feed = feedparser.parse(feed_info["url"])
            for entry in feed.entries[:30]:
                pub = None
                for attr in ("published_parsed", "updated_parsed"):
                    val = getattr(entry, attr, None)
                    if val:
                        try:
                            pub = datetime.datetime(*val[:6])
                        except Exception:
                            pass
                        break
                # Skip articles without a date, or outside yesterday's window
                if not pub or pub < win_start or pub >= win_end:
                    continue
                url = getattr(entry, "link", "")
                if not url:
                    continue
                articles.append({
                    "title": strip_html(getattr(entry, "title", "")),
                    "url": url,
                    "summary": strip_html(getattr(entry, "summary", ""))[:600],
                    "source": feed_info["name"],
                    "lang": feed_info["lang"],
                    "published_at": pub.isoformat() if pub else "",
                })
        except Exception as e:
            log(f"RSS error [{feed_info['name']}]: {e}")
    log(f"RSS: {len(articles)} articles")
    return articles



def fetch_wechat_rss():
    articles = []
    win_start = _yesterday_start()   # yesterday 00:00
    win_end = datetime.datetime.now()  # up to now (covers early-morning articles)
    for feed_info in load_wechat_feeds():
        name = feed_info.get("name", "微信公众号")
        try:
            feed = feedparser.parse(feed_info["url"])
            for entry in feed.entries[:20]:
                pub = None
                for attr in ("published_parsed", "updated_parsed"):
                    val = getattr(entry, attr, None)
                    if val:
                        try:
                            pub = datetime.datetime(*val[:6])
                        except Exception:
                            pass
                        break
                # Must have a date and fall within yesterday's window
                if not pub or pub < win_start or pub >= win_end:
                    continue
                url = getattr(entry, "link", "")
                if not url:
                    continue
                articles.append({
                    "title": strip_html(getattr(entry, "title", "")),
                    "url": url,
                    "summary": strip_html(getattr(entry, "summary", ""))[:600],
                    "source": f"微信-{name}",
                    "lang": "zh",
                    "priority": any(p in name for p in PRIORITY_ACCOUNTS),
                    "published_at": pub.isoformat() if pub else "",
                })
        except Exception as e:
            log(f"WeChat RSS error [{name}]: {e}")
    log(f"WeChat RSS: {len(articles)} articles")
    if len(articles) == 0:
        _we_mp_rss_check_token_expired()
    return articles


def _we_mp_rss_check_token_expired():
    """If WeChat RSS returned 0 articles, check we-mp-rss service availability.
    If service is down or token invalid, send a Feishu warning."""
    try:
        resp = requests.get(f"{WE_MP_RSS_ORIGIN}/api/v1/wx/mps", timeout=5)
        if resp.status_code == 401:
            log("we-mp-rss: token 失效，发送飞书警告")
            warn_msg = (
                "⚠️ 微信公众号 RSS 同步失败\n"
                "原因：we-mp-rss Token 已失效（401 错误）\n"
                "请访问 http://localhost:8001 重新扫码登录微信公众平台账号\n"
                "（今日微信公众号内容缺失，其他来源正常）"
            )
            subprocess.run(
                ["lark-cli", "im", "+messages-send",
                 "--user-id", FEISHU_USER_ID,
                 "--text", warn_msg, "--as", "user"],
                capture_output=True, text=True
            )
    except Exception as e:
        log(f"we-mp-rss token check error: {e}")


def check_wechat_token_health():
    """Evening health check: verify we-mp-rss service and token are healthy.
    Checks last article update time and service availability."""
    try:
        conn = sqlite3.connect(str(WEWE_RSS_DB))
        row = conn.execute("SELECT MAX(updated_at) FROM articles").fetchone()
        conn.close()
        last_update = row[0] if row and row[0] else 0
        hours_since_update = (time.time() - last_update) / 3600
    except Exception as e:
        print(f"WeChat token check DB error: {e}")
        return True

    token_ok = hours_since_update < 12
    print(f"WeChat token check: last article update {hours_since_update:.1f}h ago → "
          f"{'✅ OK' if token_ok else '⚠️  STALE'}")

    if not token_ok:
        warn_msg = (
            f"⚠️ 明日游戏日报预警：微信公众号数据可能未正常同步\n"
            f"原因：上次文章更新距今 {hours_since_update:.0f} 小时\n"
            f"请检查 we-mp-rss 服务：http://localhost:8001\n"
            f"若需要重新授权，请访问该地址扫码登录"
        )
        subprocess.run(
            ["lark-cli", "im", "+messages-send",
             "--user-id", FEISHU_USER_ID,
             "--text", warn_msg, "--as", "user"],
            capture_output=True, text=True
        )
    return token_ok


def _gnews_search(query, lang, hl, gl, ceid, n=10):
    """Search via Google News RSS. Returns articles with reliable pubDate."""
    url = (
        f"https://news.google.com/rss/search"
        f"?q={requests.utils.quote(query)}"
        f"&hl={hl}&gl={gl}&ceid={ceid}"
    )
    cutoff = _today_start() - datetime.timedelta(days=7)
    try:
        feed = feedparser.parse(url)
    except Exception:
        return []
    articles = []
    for entry in feed.entries[:n]:
        pub = None
        for attr in ("published_parsed", "updated_parsed"):
            val = getattr(entry, attr, None)
            if val:
                try:
                    pub = datetime.datetime(*val[:6])
                except Exception:
                    pass
                break
        if not pub or pub < cutoff:
            continue
        link = getattr(entry, "link", "")
        if not link:
            continue
        articles.append({
            "title": strip_html(getattr(entry, "title", "")),
            "url": link,
            "summary": strip_html(getattr(entry, "summary", ""))[:600],
            "source": "Google News",
            "lang": lang,
            "published_at": pub.isoformat(),
        })
    return articles


def fetch_search():
    articles = []
    for query, lang, hl, gl, ceid in SEARCH_QUERIES:
        try:
            results = _gnews_search(query, lang, hl, gl, ceid)
            articles.extend(results)
            time.sleep(0.5)
        except Exception as e:
            log(f"Google News search error [{query[:40]}]: {e}")
    log(f"Search (Google News): {len(articles)} articles")
    return articles


def fetch_focus_app_search():
    articles = []
    for name in FOCUS_GAMES:
        query = f'"{name}" mobile game analysis'
        try:
            results = _gnews_search(query, "en", "en-US", "US", "US:en", n=5)
            for article in results:
                article["source"] = f"重点游戏-{name}"
                article["priority"] = True
            articles.extend(results)
            time.sleep(0.3)
        except Exception as e:
            log(f"Focus game search error [{name}]: {e}")

    log(f"Search (重点游戏): {len(articles)} articles")
    return articles


def fetch_podcasts():
    """Fetch recent episodes from Xiaoyuzhou podcasts via RSSHub.
    Uses a 7-day window because podcasts publish weekly, not daily.
    History dedup (7 days) ensures each episode is only sent once."""
    articles = []
    win_start = _today_start() - datetime.timedelta(days=7)
    win_end = _today_start()  # up to yesterday end
    for podcast in PODCAST_FEEDS:
        url = f"{RSSHUB_BASE}/xiaoyuzhou/podcast/{podcast['id']}"
        name = podcast["name"]
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries[:15]:
                pub = None
                for attr in ("published_parsed", "updated_parsed"):
                    val = getattr(entry, attr, None)
                    if val:
                        try:
                            pub = datetime.datetime(*val[:6])
                        except Exception:
                            pass
                        break
                if not pub or pub < win_start or pub >= win_end:
                    continue
                link = getattr(entry, "link", "")
                if not link:
                    continue
                articles.append({
                    "title": strip_html(getattr(entry, "title", "")),
                    "url": link,
                    "summary": strip_html(getattr(entry, "summary", ""))[:600],
                    "source": f"播客-{name}",
                    "lang": "zh",
                    "published_at": pub.isoformat(),
                })
        except Exception as e:
            log(f"Podcast RSS error [{name}]: {e}")
    log(f"Podcast (小宇宙): {len(articles)} episodes")
    return articles


def fetch_on_this_day():
    """Query WeWe-RSS local SQLite DB for articles published on the same month/day
    in the previous ON_THIS_DAY_YEARS years. Returns all matches with no score filter."""
    if not WEWE_RSS_DB.exists():
        log("On This Day: WeWe-RSS database not found, skipping")
        return []

    today = _TARGET_DATE if _TARGET_DATE else datetime.datetime.now()
    month_day = today.strftime("%m-%d")  # e.g. "05-26"
    target_years = [today.year - i for i in range(1, ON_THIS_DAY_YEARS + 1)]

    articles = []
    try:
        conn = sqlite3.connect(str(WEWE_RSS_DB))
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        placeholders = ",".join("?" * len(target_years))
        cur.execute(f"""
            SELECT a.id, a.title, f.mp_name,
                   strftime('%Y-%m-%d', a.publish_time, 'unixepoch') as pub_date,
                   strftime('%Y', a.publish_time, 'unixepoch') as pub_year
            FROM articles a
            JOIN feeds f ON a.mp_id = f.id
            WHERE strftime('%m-%d', a.publish_time, 'unixepoch') = ?
              AND strftime('%Y',  a.publish_time, 'unixepoch') IN ({placeholders})
            ORDER BY a.publish_time DESC
        """, [month_day] + [str(y) for y in target_years])

        for row in cur.fetchall():
            articles.append({
                "title": row["title"],
                "url": f"https://mp.weixin.qq.com/s/{row['id']}",
                "summary": "",
                "source": f"微信-{row['mp_name']}",
                "lang": "zh",
                "published_at": row["pub_date"],
                "on_this_day_year": int(row["pub_year"]),
            })
        conn.close()
    except Exception as e:
        log(f"On This Day error: {e}")

    log(f"On This Day: {len(articles)} articles ({month_day} in {target_years})")
    return articles


CAMOUFOX_TOOL = Path.home() / ".agent-reach/tools/wechat-article-for-ai"
CAMOUFOX_OUTPUT = CAMOUFOX_TOOL / "output"


def _fetch_wechat_content(url):
    """Fetch full text of a WeChat article via Camoufox (--no-images for speed).
    Returns markdown text, or empty string on failure."""
    try:
        result = subprocess.run(
            ["python3", "main.py", url, "--no-images", "--no-frontmatter"],
            cwd=str(CAMOUFOX_TOOL),
            capture_output=True, text=True, timeout=60
        )
        # Find the output markdown file
        if result.returncode != 0:
            return ""
        # Locate the newest .md file written
        md_files = sorted(CAMOUFOX_OUTPUT.rglob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
        if not md_files:
            return ""
        content = md_files[0].read_text(encoding="utf-8")
        # Strip image references to keep only text
        content = re.sub(r'!\[.*?\]\(.*?\)', '', content)
        content = re.sub(r'\n{3,}', '\n\n', content)
        return content[:4000]  # cap to avoid huge prompts
    except Exception as e:
        log(f"Camoufox fetch error [{url[:60]}]: {e}")
        return ""


def translate_on_this_day(articles):
    """Fetch full content of each On This Day article via Camoufox,
    then ask Claude to generate a 2-sentence summary."""
    if not articles:
        return articles

    for a in articles:
        log(f"On This Day: fetching content for 《{a['title'][:30]}》")
        content = _fetch_wechat_content(a["url"])
        if not content:
            a["zh_desc"] = ""
            continue
        prompt = f"""以下是一篇微信公众号文章的正文（来源：{a['source']}，发布于 {a['on_this_day_year']} 年）：

{content}

请用 2 句话概括这篇文章的核心内容和对游戏从业者的参考价值（总计不超过 80 字）。
只输出这 2 句话，不要任何其他内容。"""
        # Retry once with a short delay — may fail right after batch scoring
        for attempt in range(2):
            try:
                a["zh_desc"] = claude_call(prompt)
                break
            except Exception as e:
                err_msg = str(e) if str(e) else repr(e)
                if attempt == 0:
                    log(f"On This Day summarize retry (attempt {attempt+1}): {err_msg}")
                    import time; time.sleep(8)
                else:
                    log(f"On This Day summarize failed: {err_msg}")
                    a["zh_desc"] = ""

    return articles


def fetch_wechat():
    """Search WeChat via Sogou (official WeChat search engine).
    Links are Sogou redirect URLs that open correctly in a browser."""
    articles = []
    session = requests.Session()
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept-Language": "zh-CN,zh;q=0.9",
        "Referer": "https://weixin.sogou.com/",
    }
    try:
        session.get("https://weixin.sogou.com/", headers=headers, timeout=10)
    except Exception:
        pass

    for query in WECHAT_QUERIES:
        try:
            url = f"https://weixin.sogou.com/weixin?query={requests.utils.quote(query)}&type=2&tsn=1"
            resp = session.get(url, headers=headers, timeout=15)
            soup = BeautifulSoup(resp.text, "html.parser")
            for item in soup.select(".news-list li"):
                title_el = item.select_one("h3 a")
                summary_el = item.select_one(".txt-info")
                account_el = item.select_one("span.account") or item.select_one(".s-p em") or item.select_one(".s-p")
                date_el = item.select_one(".s2") or item.select_one(".time")
                if not title_el:
                    continue
                href = title_el.get("href", "")
                # Skip account homepages — only keep article redirect links
                if not href.startswith("/link"):
                    continue
                link = "https://weixin.sogou.com" + href
                account_name = account_el.get_text(strip=True) if account_el else ""
                is_priority = any(p in account_name for p in PRIORITY_ACCOUNTS)
                published_at = date_el.get_text(strip=True) if date_el else item.get_text(" ", strip=True)
                articles.append({
                    "title": title_el.get_text(strip=True),
                    "url": link,
                    "summary": summary_el.get_text(strip=True) if summary_el else "",
                    "source": f"微信-{account_name}" if account_name else "微信公众号",
                    "lang": "zh",
                    "priority": is_priority,
                    "published_at": published_at,
                })
            time.sleep(2)
        except Exception as e:
            log(f"Sogou WeChat error [{query}]: {e}")

    articles = filter_fresh(articles, require_date=True, label="WeChat freshness")
    log(f"Search (WeChat/Sogou): {len(articles)} articles")
    return articles


def claude_call(prompt_text, _retry=3):
    """Call claude CLI non-interactively and return stdout.
    Retries up to _retry times on auth/rate-limit errors (e.g. right after Mac wakes from sleep).
    3 retries × 5 min = up to 15 min total, covering the OAuth token refresh window after wake."""
    import os
    env = os.environ.copy()
    env.setdefault("HOME", str(Path.home()))
    env.setdefault("USER", os.environ.get("USER", "xiongxiong"))
    env.setdefault("PATH", "/Users/xiongxiong/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin")
    result = subprocess.run(
        ["claude", "-p", prompt_text, "--output-format", "text"],
        capture_output=True, text=True, timeout=300, env=env
    )
    if result.returncode != 0:
        detail = (result.stderr.strip() or result.stdout.strip() or f"exit {result.returncode}")[:500]
        # Auth/rate-limit errors can occur right after Mac wakes from sleep.
        # Wait 5 minutes and retry — OAuth token usually refreshes within 15 min.
        if _retry > 0 and any(kw in detail.lower() for kw in
                               ["credit balance", "usage limit", "oauth token", "not logged in",
                                "authentication failed", "unauthorized"]):
            log(f"Claude call error (retrying in 300s, {_retry} left): {detail}")
            import time; time.sleep(300)
            return claude_call(prompt_text, _retry=_retry - 1)
        raise RuntimeError(detail)
    return result.stdout.strip()


def score_and_translate_batch(articles):
    if not articles:
        return []

    def clean(s):
        return re.sub(r'[\x00-\x1f\x7f]', ' ', (s or "")).replace('"', "'").strip()

    payload = json.dumps(
        [{"i": i, "title": clean(a["title"]), "summary": clean(a["summary"]),
          "url": a.get("url", "")[:100], "lang": a["lang"], "source": a["source"],
          "priority": a.get("priority", False), "published_at": a.get("published_at", "")}
         for i, a in enumerate(articles)],
        ensure_ascii=False
    )

    _ref = _TARGET_DATE if _TARGET_DATE else datetime.datetime.now()
    today = _ref.strftime("%Y年%m月%d日")
    today_start = _today_start().strftime("%Y年%m月%d日 00:00")
    tomorrow_start = _tomorrow_start().strftime("%Y年%m月%d日 00:00")
    old_year = _ref.year - 1
    prompt = f"""你是休闲游戏分析专家，专注于三消/消除类手游（如 Royal Match、Candy Crush、Homescapes 等）的设计、运营和变现研究。

今天是 {today}。请处理以下文章列表：
{payload}

**第一步：评分（1-10）**
- 9-10：深度拆解休闲游戏玩法/关卡设计/数值/变现/LiveOps 的专业文章
- 7-8：有实质内容的游戏设计分析，与休闲/手游相关
- 5-6：一般性游戏行业资讯，相关度一般
- 3-4：泛游戏内容，与休闲游戏几乎无关
- 1-2：广告、无实质内容、或完全不相关；官网/产品页/应用商店页面也给 1 分

**重要：时效性过滤**
以下情况直接给 1 分，不论内容质量：
- published_at 字段有值且明确显示是 {old_year} 年或更早
- 标题或摘要明确说明是对 {old_year} 年或更早的年度总结/回顾报告（如"2025年度报告"、"2024全年数据"）
- URL 路径中包含 /{old_year}/ 或更早年份

注意：published_at 为空不扣分。文章中引用历史数据作为对比是正常的，不要因此扣分。

**第二步：分类（category 字段，与 score 独立判断）**
根据文章实际内容，直接指定以下三类之一，不要依赖分数边界推断：
- "深度拆解"：文章核心是对游戏玩法/机制/数值/变现/LiveOps/关卡设计进行专业分析拆解
- "行业资讯"：游戏行业新闻、市场动态、公司动态、数据报告、新游发布等
- "泛游戏"：游戏体验分享、评测、游戏文化、娱乐向内容，与行业分析关联较弱"""
    prompt += """

**优先公众号加权：** 以下公众号是经过筛选的高质量游戏分析账号，如果文章的 source 字段包含这些名称之一，或 priority 字段为 true，在基础分上额外加 1 分（但不超过 10 分）：
王董的新游戏、一枚游戏干饭人、GAME游意思、DennisLook、游戏译文、良明同学、海外新游精选、Enjoy出海开发者服务平台、Vergil的游戏杂谈、新游观察、柠檬游戏说、曾嵘胡扯的地方、熊猫搞钱记、龙虎游戏推荐、游戏进化论、无界游戏学社、罗斯基、Crazy Labs、星空出海、嘅噗喔呋啼。

对每篇文章输出：
1. score：整数评分
2. category：分类，只能是 "深度拆解" / "行业资讯" / "泛游戏" 之一
3. zh_title：精准的中文标题（英文需翻译，中文可优化）
4. zh_desc：2-3句中文摘要，说明核心内容和对从业者的价值

返回严格的 JSON 数组，格式：
[{"i": 0, "score": 8, "category": "深度拆解", "zh_title": "...", "zh_desc": "..."}]

只返回 JSON 数组，不要任何其他文字或代码块标记。"""

    try:
        raw = claude_call(prompt)
    except Exception as e:
        log(f"Claude call error: {e}")
        # 降级：评分失败时给所有候选文章打默认分数，确保日报仍能发出
        log("Claude 评分失败，降级处理：所有候选文章使用默认评分发送")
        fallback = []
        for article in articles:
            article["score"] = MIN_SCORE
            article["category"] = "行业资讯"
            article["zh_title"] = article.get("title", "")
            article["zh_desc"] = article.get("summary", "")[:200]
            fallback.append(article)
        return fallback

    results = _parse_json_robust(raw)
    if results is None:
        log(f"Claude scoring error: could not parse JSON from response")
        return []

    def _score_to_category(score):
        if score >= 7:
            return "深度拆解"
        elif score >= 5:
            return "行业资讯"
        else:
            return "泛游戏"

    result_map = {r["i"]: r for r in results if isinstance(r, dict) and "i" in r}
    scored = []
    for i, article in enumerate(articles):
        r = result_map.get(i, {})
        score = r.get("score", 0)
        if score >= MIN_SCORE:
            article["score"] = score
            # Use explicit category from Claude; fall back to score-based if missing
            article["category"] = r.get("category") or _score_to_category(score)
            article["zh_title"] = r.get("zh_title", article["title"])
            article["zh_desc"] = r.get("zh_desc", article["summary"])
            scored.append(article)
    return scored


def _parse_json_robust(raw):
    """Try multiple strategies to parse a JSON array from Claude's response."""
    # Strip code fences
    raw = re.sub(r"^```\w*\n?|```\s*$", "", raw.strip()).strip()

    # Strategy 1: direct parse
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass

    # Strategy 2: find the outermost [...] and parse
    m = re.search(r"\[.*\]", raw, re.DOTALL)
    if m:
        try:
            return json.loads(m.group())
        except json.JSONDecodeError:
            pass

    # Strategy 3: extract individual {...} objects via regex and parse each
    objects = re.findall(r'\{[^{}]*\}', raw, re.DOTALL)
    results = []
    for obj in objects:
        try:
            results.append(json.loads(obj))
        except json.JSONDecodeError:
            pass
    if results:
        return results

    return None


def format_message(articles, date_str, on_this_day=None):
    # Group by explicit category assigned by Claude
    deep    = [a for a in articles if a.get("category") == "深度拆解"]
    news    = [a for a in articles if a.get("category") == "行业资讯"]
    general = [a for a in articles if a.get("category") == "泛游戏"]

    # Feishu plain-text format — no markdown (** [] _ --- are rendered literally)
    lines = [
        f"🎮 休闲游戏分析日报 · {date_str}  共 {len(articles)} 篇",
    ]

    sections = [
        ("🔥 深度拆解休闲游戏玩法", deep),
        ("📊 游戏行业资讯",          news),
        ("🕹️ 泛游戏内容",            general),
    ]

    idx = 1
    for section_title, group in sections:
        if not group:
            continue
        lines.append(f"\n━━ {section_title}\n")
        for a in group:
            title = a['zh_title'].replace('《', '').replace('》', '')
            lines.append(f"{idx}. {title}")
            if a.get("zh_desc"):
                lines.append(a["zh_desc"])
            lines.append(f"来源：{a['source']}")
            lines.append(a["url"] + "\n")
            idx += 1

    # On This Day section
    if on_this_day:
        # Group by year
        by_year = {}
        for a in on_this_day:
            y = a["on_this_day_year"]
            by_year.setdefault(y, []).append(a)

        lines.append("\n━━ 📅 往年今日（{month_day}）\n".format(
            month_day=date_str[5:]))
        for year in sorted(by_year.keys(), reverse=True):
            lines.append(f"▎{year}年")
            for a in by_year[year]:
                lines.append(f"· {a['title'].replace('《', '').replace('》', '')}")
                if a.get("zh_desc"):
                    lines.append(f"  {a['zh_desc']}")
                lines.append(f"  来源：{a['source']}")
                lines.append(f"  {a['url']}")
            lines.append("")

    lines.append("由 Claude 自动整理，每日 09:00 触发发送")
    return "\n".join(lines)


def send_feishu(message, test_mode=False):
    if test_mode:
        # Test: send to personal chat only
        cmd = ["lark-cli", "im", "+messages-send",
               "--user-id", FEISHU_USER_ID,
               "--text", message, "--as", "user"]
        target = f"user:{FEISHU_USER_ID}"
    else:
        # Production: send to group chat
        cmd = ["lark-cli", "im", "+messages-send",
               "--chat-id", FEISHU_CHAT_ID,
               "--text", message, "--as", "user"]
        target = f"chat:{FEISHU_CHAT_ID}"

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        log(f"Feishu error: {result.stderr}")
        return False
    log(f"Feishu: sent successfully → {target}")
    return True


def main(test_mode=False):
    log("=== Game Digest Start ===" + (" [TEST MODE]" if test_mode else ""))

    # 防重复发送：当天已有存档文件则跳过（test_mode 和手动指定日期除外）
    if not test_mode and not _TARGET_DATE:
        today_archive = ARCHIVE_DIR / f"{datetime.datetime.now().strftime('%Y-%m-%d')}.md"
        if today_archive.exists():
            log(f"今日日报已发送（{today_archive.name}），跳过重复运行")
            return

    # Collect
    on_this_day = fetch_on_this_day()
    all_articles = fetch_wechat_rss() + fetch_rss() + fetch_podcasts() + fetch_search() + fetch_focus_app_search()
    if ENABLE_SOGOU_WECHAT:
        all_articles += fetch_wechat()
    else:
        log("Search (WeChat/Sogou): disabled")

    # Remove blocked domains (official game sites, app stores, social media)
    all_articles = filter_blocked(all_articles)

    # Remove articles whose URL contains an old year (e.g. /2025/ or /2024/)
    before = len(all_articles)
    all_articles = [a for a in all_articles if not _contains_old_year(a)]
    removed = before - len(all_articles)
    if removed:
        log(f"Old URL year removed: {removed}")

    # Dedup within batch (same article from multiple sources)
    all_articles = dedup_batch(all_articles)
    log(f"After batch dedup: {len(all_articles)}")

    # Dedup against history (skip in test mode)
    if test_mode:
        log("History dedup: skipped (test mode)")
        candidates_pool = all_articles
    else:
        history = load_history()
        log(f"History: {len(history['articles'])} entries (last {DEDUP_DAYS} days)")
        candidates_pool = [a for a in all_articles if not is_duplicate(a, history)]
        log(f"After history dedup: {len(candidates_pool)}")

    if not candidates_pool:
        log("No articles today. Skipping send.")
        return

    candidates = sort_candidate_articles(candidates_pool)[:MAX_CANDIDATES_TO_SCORE]
    log(f"Candidates selected for scoring: {len(candidates)}")

    # Score + translate in batches of 20 (balance: fewer CLI cold-starts vs timeout risk)
    scored = []
    BATCH = 20
    for i in range(0, len(candidates), BATCH):
        batch_result = score_and_translate_batch(candidates[i:i + BATCH])
        scored.extend(batch_result)
    log(f"After scoring (≥{MIN_SCORE}): {len(scored)} articles")

    # Generate descriptions for On This Day articles (title-only, bypass score filter)
    if on_this_day:
        on_this_day = translate_on_this_day(on_this_day)

    if not scored:
        log("No articles scored above threshold today.")
        return

    # Sort by score desc within each category (format_message handles grouping)
    scored.sort(key=lambda x: x["score"], reverse=True)
    log(f"Sending {len(scored)} articles")

    # Format and send — use target date if backfilling, otherwise today
    report_date = _TARGET_DATE if _TARGET_DATE else datetime.datetime.now()
    date_str = report_date.strftime("%Y年%m月%d日")
    message = format_message(scored, date_str, on_this_day=on_this_day or None)
    send_feishu(message, test_mode=test_mode)

    # Save local backup
    ARCHIVE_DIR.mkdir(exist_ok=True)
    suffix = "_test" if test_mode else ""
    archive_file = ARCHIVE_DIR / f"{report_date.strftime('%Y-%m-%d')}{suffix}.md"
    with open(archive_file, "w", encoding="utf-8") as f:
        f.write(message)
    log(f"Saved: {archive_file.name}")

    # Save to history (skip in test mode to avoid polluting dedup)
    if not test_mode:
        save_history(history, scored)

    log(f"=== Done: {len(scored)} articles sent ===")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--check-wechat-feeds":
        raise SystemExit(check_wechat_feeds())
    if "--health-check" in sys.argv:
        ok = check_wechat_token_health()
        raise SystemExit(0 if ok else 1)
    # --date YYYY-MM-DD  → run digest for a specific past date
    if "--date" in sys.argv:
        idx = sys.argv.index("--date")
        _TARGET_DATE = datetime.datetime.strptime(sys.argv[idx + 1], "%Y-%m-%d")
    test_mode = "--test" in sys.argv
    main(test_mode=test_mode)
